name: Test

on:
  workflow_call:

jobs:
  build:
    name: Test ${{ matrix.arch }}-${{ matrix.release }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 23.05.3
        arch:
          - x86_64

    steps:
      - uses: actions/checkout@v4

      - name: Add test directories
        run: mkdir artifacts feed

      - name: Build
        uses: ./
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feed
          PACKAGES: openconnect
          CONFIG_OPENCONNECT_OPENSSL: y

      - name: Verify packages saved
        run: find artifacts/bin/packages/${{ matrix.arch }}/packages/ -maxdepth 1 -name '*.[ai]pk' -type f | grep .

      - name: Verify logs saved
        run: find artifacts/logs/package/feeds/packages/ -mindepth 2 -maxdepth 2 -name compile.txt -type f | grep .

      - name: Store packages
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}-packages
          path: artifacts/bin/packages/${{ matrix.arch }}/packages/*.ipk
